name: Build and publish

on:
  release:
    types: [published]
  push:
    branches: [CI-publish-test]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: all
          args: --release
          manylinux: auto

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
          user: "${{env.PYPI_USER}}"
          password: "${{env.PYPI_PASS}}"
